version: '3'

services:
  mongo-cron-backup:
    build: .
    environment:
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      # Uncomment if auth is required
      # - MONGODB_USERNAME=${MONGODB_USERNAME}
      # - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      # - MONGODB_AUTH_DATABASE=${MONGODB_AUTH_DATABASE}
      - CRON_EXPRESSION=${CRON_EXPRESSION}
      - LOCAL_PATH=${LOCAL_PATH}
      - DESTINATION_PATH=${DESTINATION_PATH}
      - OAUTH_ACCESS_TOKEN=${OAUTH_ACCESS_TOKEN}
    image: thelebster/mongo-cron-backup
    hostname: mongo-cron-backup
    container_name: mongo-cron-backup
    restart: always
    # Uncomment if runs on the same host and you will be able to access mongo on 127.0.0.1:27017
    # network_mode: "host"
    volumes:
      - ${LOCAL_PATH}:${DESTINATION_PATH}
